name: Deploy

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/main.yml'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn testci

      - name: Build project
        run: yarn build

      - name: Zip build
        run: (cd dist && zip -r ../deploy.zip .)

      - name: Deploy to AWS
        run: aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file=fileb://deploy.zip
